### ISSUE TITLE
Merge .bed file features generated from both sequence directions into one file

### ISSUE THREAD

**Issue by AlistairNGarratt** [AnthyG/Z-DNABERT#1]
Currently, Z-DNA elements in plus and minus strand sequences are provided as separate bed files. Z-DNA elements in bed files should be merged, but the direction of the features should remain distinguishable upon automatic import into sequencing software, e.g. as a feature description

**Comment by AnthyG** [comment]
I have pushed the changes into the branch [without-cuda](https://github.com/AnthyG/Z-DNABERT/tree/without-cuda) https://github.com/AnthyG/Z-DNABERT/commit/0f27abcc658dda66ccc8cc1ac6d89b6104cd1c2f

I also incorporated the model name and parameters into the feature descriptions.

**Comment by AnthyG** [comment]
I tried out using the 6th field of the bed file format (see https://grch37.ensembl.org/info/website/upload/bed.html#optional) but I found it confusing when reversing the sequence in the sequence software. I think it refers to the absolute strand direction (plus and minus), but as we discussed before, this is not applicable to the relative direction we are working with in the notebook (because the notebook can also accept reversed fasta inputs).

**Comment by AlistairNGarratt** [comment]
Hi Anthony,

Maybe merging the files is not optimal as the sequence software Snapgene
can’t independently draw direction arrows for one set of features in the
.bed file, although some run on minus strand, some on plus.

**Comment by AnthyG** [comment]
In the end I used the "name" field instead. In there, they are differentiated by "normal" and "reverse-complement"
