### ISSUE TITLE
Including running time-stamp and parameters in bed file names

### ISSUE THREAD

**Issue by AlistairNGarratt** [AnthyG/Z-DNABERT#2]
Please include a time-stamp and model,confidence,sequence-length in name of bed files so that each bed file has a unique name and cannot be overwritten. Thank you. A Garratt

**Comment by AnthyG** [comment]
I had to implement a check to ensure that the generated files names don't exceed operating system file name length limits.
For this, I decided to hard code 255 as the maximum file name length, as it seems to be the most common maximum length among different systems: https://en.wikipedia.org/wiki/Comparison_of_file_systems#Limits

Because of this limit, a good maximum length for an input file name is probably around 180 characters, as all of the stuff that gets added is about 80 characters.

When at least one of the generated file names exceeds the maximum length, an error will be thrown, e.g.:

![example of multiple generated file names exceeding the maximum file name length](https://github.com/AnthyG/Z-DNABERT/assets/15957203/09d8eb92-bfdb-4262-92dd-002f9d95b966)
